# Generated by Django 6.1.1 on 2026-09-21 14:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('color', models.CharField(default='#ff6f59', max_length=7)),
                ('size', models.PositiveSmallIntegerField(default=110, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(200)])),
                ('speed', models.PositiveSmallIntegerField(default=16, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(40)])),
                ('depth', models.PositiveSmallIntegerField(default=40)),
                ('meals', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'fish',
                'ordering': ['id'],
            },
        ),
    ]
